/*
 * Copyright (C) Ascensio System SIA 2012-2020. All rights reserved
 *
 * https://www.onlyoffice.com/
 *
 * Version: 0.0.0 (build:0)
 */

(function(f,e){function Ia(e){return Xa.locateFile?Xa.locateFile(e,Fe):Fe+e}function eb(e,f,z){var La=f+z;for(z=f;e[z]&&!(z>=La);)++z;if(16<z-f&&e.subarray&&Zd)return Zd.decode(e.subarray(f,z));for(La="";f<z;){var Qa=e[f++];if(Qa&128){var x=e[f++]&63;if(192==(Qa&224))La+=String.fromCharCode((Qa&31)<<6|x);else{var Oa=e[f++]&63;Qa=224==(Qa&240)?(Qa&15)<<12|x<<6|Oa:(Qa&7)<<18|x<<12|Oa<<6|e[f++]&63;65536>Qa?La+=String.fromCharCode(Qa):(Qa-=65536,La+=String.fromCharCode(55296|Qa>>10,56320|Qa&1023))}}else La+=
String.fromCharCode(Qa)}return La}function bb(e){vh=e;Xa.HEAP8=ce=new Int8Array(e);Xa.HEAP16=new Int16Array(e);Xa.HEAP32=rb=new Int32Array(e);Xa.HEAPU8=Ab=new Uint8Array(e);Xa.HEAPU16=new Uint16Array(e);Xa.HEAPU32=new Uint32Array(e);Xa.HEAPF32=new Float32Array(e);Xa.HEAPF64=new Float64Array(e)}function cb(f){for(;0<f.length;){var z=f.shift();if("function"==typeof z)z();else{var La=z.func;"number"===typeof La?z.w1f===e?Xa.dynCall_v(La):Xa.dynCall_vi(La,z.w1f):La(z.w1f===e?null:z.w1f)}}}function z(e){if(Xa.onAbort)Xa.onAbort(e);
e+="";Eg(e);Dh(e);yd=!0;throw new WebAssembly.u9g("abort("+e+"). Build with -s ASSERTIONS=1 for more info.");}function zb(e){return String.prototype.startsWith?e.startsWith("data:application/octet-stream;base64,"):0===e.indexOf("data:application/octet-stream;base64,")}function Wb(){try{if(ue)return new Uint8Array(ue);if(Je)return Je(Yj);throw"both async and sync fetching of the wasm failed";}catch(Yf){z(Yf)}}function kb(){return ue||!De&&!jf||"function"!==typeof yb?new Promise(function(e){e(Wb())}):
yb(Yj,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+Yj+"'";return e.arrayBuffer()}).catch(function(){return Wb()})}function Za(e,f,z,La){e|=0;f|=0;z|=0;La|=0;var Qa=0;qc=qc+1|0;for(rb[e>>2]=qc;(Qa|0)<(La|0);){if(0==(rb[z+(Qa<<3)>>2]|0))return rb[z+(Qa<<3)>>2]=qc,rb[z+((Qa<<3)+4)>>2]=f,rb[z+((Qa<<3)+8)>>2]=0,Mf=La|0,z|0;Qa=Qa+1|0}La=2*La|0;z=Oi(z|0,8*(La+1|0)|0)|0;z=Za(e|0,f|0,z|0,La|0)|0;Mf=La|0;return z|0}function Mb(){if(!Mb.Cta){var e={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Qa},f;for(f in pl)e[f]=pl[f];var z=[];for(f in e)z.push(f+"="+e[f]);Mb.Cta=z}return Mb.Cta}function Ta(){function e(){if(!Ie&&(Ie=!0,!yd)){cb(wf);cb(Uh);if(Xa.onRuntimeInitialized)Xa.onRuntimeInitialized();if(Xa.postRun)for("function"==typeof Xa.postRun&&(Xa.postRun=[Xa.postRun]);Xa.postRun.length;)pe.unshift(Xa.postRun.shift());
cb(pe)}}if(!(0<rc)){if(Xa.preRun)for("function"==typeof Xa.preRun&&(Xa.preRun=[Xa.preRun]);Xa.preRun.length;)og.unshift(Xa.preRun.shift());cb(og);0<rc||(Xa.setStatus?(Xa.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Xa.setStatus("")},1);e()},1)):e())}}function pb(){this.h3d=this.MSc=this.U8b=this.uM=this.nJc=this.u0=this.height=this.R_=this.N7=this.GUa=0;this.iHa=this.b7="";this.Gxg=this.Hxg=this.lCg=this.nCg=this.mCg=this.Qbg=this.Pbg=this.oCg=this.Sbg=this.Rbg=this.kCg=this.pCg=
this.TPf=0;this.oPf=[]}function sc(){this.GRc=this.WHc=this.pHa=this.IIa=this.Lna=this.nua=this.Txa=this.roa=this.height=this.width=this.Msg=this.Ksg=this.Nsg=this.Lsg=0}function kc(){this.mode=this.pitch=this.rows=this.width=this.top=this.left=0}var nc=f.AscFonts,yb=f.fetch,La=null;f.AscDesktopEditor&&document.currentScript&&0==document.currentScript.src.indexOf("file:///")?(yb=e,La=function(){var e="ascdesktop://fonts/"+Yj.substr(8);return new Promise(function(f){var z=new XMLHttpRequest;z.open("GET",
e,!0);z.responseType="arraybuffer";z.overrideMimeType?z.overrideMimeType("text/plain; charset=x-user-defined"):z.setRequestHeader("Accept-Charset","x-user-defined");z.onload=function(){200==this.status&&f(new Uint8Array(this.response))};z.send(null)})}):La=function(){return kb()};var Xa="undefined"!==typeof Xa?Xa:{},lb={};for(Ze in Xa)Xa.hasOwnProperty(Ze)&&(lb[Ze]=Xa[Ze]);var Qa="./this.program",De=!0,jf=!1,Fe="",Je;if(De||jf)jf?Fe=self.location.href:document.currentScript&&(Fe=document.currentScript.src),
Fe=0!==Fe.indexOf("blob:")?Fe.substr(0,Fe.lastIndexOf("/")+1):"",jf&&(Je=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.responseType="arraybuffer";f.send(null);return new Uint8Array(f.response)});var Eg=Xa.print||console.log.bind(console),Dh=Xa.printErr||console.warn.bind(console);for(Ze in lb)lb.hasOwnProperty(Ze)&&(Xa[Ze]=lb[Ze]);lb=null;Xa.thisProgram&&(Qa=Xa.thisProgram);var Mf=0,ue;Xa.wasmBinary&&(ue=Xa.wasmBinary);"object"!==typeof WebAssembly&&Dh("no native wasm support detected");
var $c;lb=new WebAssembly.Table({initial:573,maximum:573,element:"anyfunc"});var yd=!1,Zd="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):e;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ce,Ab,rb;var Ze=Xa.TOTAL_MEMORY||16777216;if($c=Xa.wasmMemory?Xa.wasmMemory:new WebAssembly.Memory({initial:Ze/65536}))var vh=$c.buffer;Ze=vh.byteLength;bb(vh);rb[27492]=5353008;var og=[],wf=[],Uh=[],pe=[function(){f.AscFonts.OJb()}],rc=0,Kd=null,kf=null;Xa.preloadedImages={};Xa.preloadedAudios=
{};var Yj="fonts.wasm";zb(Yj)||(Yj=Ia(Yj));wf.push({func:function(){Wd()}});var wh={JTa:[null,[],[]],u3g:function(e,f){var z=wh.JTa[e];0===f||10===f?((1===e?Eg:Dh)(eb(z,0)),z.length=0):z.push(f)},cae:0,get:function(){wh.cae+=4;return rb[wh.cae-4>>2]},L5a:function(){var e=wh.get();return e?eb(Ab,e,void 0):""},P$g:function(){var e=wh.get();wh.get();return e},V$g:function(){wh.get()}},qc=0,pl={},id={v:function(){},f:function(e,f){wh.cae=f;return 0},i:function(f,La){wh.cae=La;try{var Qa=wh.L5a(),Ta=wh.get(),
Za=wh.get();return e.open(Qa,Ta,Za).J$g}catch(x){return"undefined"!==typeof e&&x instanceof e.rkg||z(x),-x.vvg}},u:function(e,f){wh.cae=f;return 0},e:function(){},b:function(e,f){Ee(e,f||1);throw"longjmp";},n:function(e,f,z){Ab.set(Ab.subarray(f,f+z),e)},p:function(e){var f=ce.length;if(2147418112<e)return!1;for(var z=1;4>=z;z*=2){var La=f*(1+.2/z);La=Math.min(La,e+100663296);La=Math.max(16777216,e,La);0<La%65536&&(La+=65536-La%65536);a:{try{$c.grow(Math.min(2147418112,La)-vh.byteLength+65535>>16);
bb($c.buffer);var Qa=1;break a}catch(x){}Qa=void 0}if(Qa)return!0}return!1},q:function(e,f){var z=0;Mb().forEach(function(La,Qa){var x=f+z;Qa=rb[e+4*Qa>>2]=x;for(x=0;x<La.length;++x)ce[Qa++>>0]=La.charCodeAt(x);ce[Qa>>0]=0;z+=La.length+1});return 0},r:function(e,f){var z=Mb();rb[e>>2]=z.length;var La=0;z.forEach(function(e){La+=e.length+1});rb[f>>2]=La;return 0},g:function(){return 0},t:function(f,La,Qa,Ta){try{var Za=wh.U$g(f),x=wh.F$g(Za,La,Qa);rb[Ta>>2]=x;return 0}catch(Oa){return"undefined"!==
typeof e&&Oa instanceof e.rkg||z(Oa),Oa.vvg}},m:function(){return 0},s:function(f,La,Qa,Ta){try{for(var Za=0,x=0;x<Qa;x++){for(var Oa=rb[La+8*x>>2],Ia=rb[La+(8*x+4)>>2],lb=0;lb<Ia;lb++)wh.u3g(f,Ab[Oa+lb]);Za+=Ia}rb[Ta>>2]=Za;return 0}catch(un){return"undefined"!==typeof e&&un instanceof e.rkg||z(un),un.vvg}},a:function(){return Mf|0},k:function(e,f,z){var La=md();try{return Yc(e,f,z)}catch(mg){pc(La);if(mg!==mg+0&&"longjmp"!==mg)throw mg;Ee(1,0)}},o:function(e,f,z,La){var Qa=md();try{return Vi(e,
f,z,La)}catch(x){pc(Qa);if(x!==x+0&&"longjmp"!==x)throw x;Ee(1,0)}},j:function(e,f,z,La,Qa){var x=md();try{return we(e,f,z,La,Qa)}catch(Oa){pc(x);if(Oa!==Oa+0&&"longjmp"!==Oa)throw Oa;Ee(1,0)}},l:function(e,f,z){var La=md();try{Ke(e,f,z)}catch(mg){pc(La);if(mg!==mg+0&&"longjmp"!==mg)throw mg;Ee(1,0)}},memory:$c,h:Za,c:function(e){Mf=e|0},table:lb,d:function(e,f,z){e|=0;f|=0;z|=0;for(var La=0,Qa;(La|0)<(z|0);){Qa=rb[f+(La<<3)>>2]|0;if(0==(Qa|0))break;if((Qa|0)==(e|0))return rb[f+((La<<3)+4)>>2]|0;
La=La+1|0}return 0}};lb=function(){function e(e){Xa.asm=e.exports;rc--;Xa.monitorRunDependencies&&Xa.monitorRunDependencies(rc);0==rc&&(null!==Kd&&(clearInterval(Kd),Kd=null),kf&&(e=kf,kf=null,e()))}function f(f){e(f.instance)}function Qa(e){return La().then(function(e){return WebAssembly.instantiate(e,Ta)}).then(e,function(e){Dh("failed to asynchronously prepare wasm: "+e);z(e)})}var Ta={a:id};rc++;Xa.monitorRunDependencies&&Xa.monitorRunDependencies(rc);if(Xa.instantiateWasm)try{return Xa.instantiateWasm(Ta,
e)}catch(mg){return Dh("Module.instantiateWasm callback failed with error: "+mg),!1}(function(){if(ue||"function"!==typeof WebAssembly.instantiateStreaming||zb(Yj)||"function"!==typeof yb)return Qa(f);yb(Yj,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,Ta).then(f,function(e){Dh("wasm streaming compile failed: "+e);Dh("falling back to ArrayBuffer instantiation");Qa(f)})})})();return{}}();Xa.asm=lb;var Wd=Xa.___wasm_call_ctors=function(){return(Wd=Xa.___wasm_call_ctors=
Xa.asm.w).apply(null,arguments)};Xa._FT_Load_Glyph=function(){return(Xa._FT_Load_Glyph=Xa.asm.x).apply(null,arguments)};Xa._FT_Set_Transform=function(){return(Xa._FT_Set_Transform=Xa.asm.y).apply(null,arguments)};Xa._FT_Done_Face=function(){return(Xa._FT_Done_Face=Xa.asm.z).apply(null,arguments)};Xa._FT_Set_Char_Size=function(){return(Xa._FT_Set_Char_Size=Xa.asm.A).apply(null,arguments)};Xa._FT_Get_Glyph=function(){return(Xa._FT_Get_Glyph=Xa.asm.B).apply(null,arguments)};Xa._FT_Done_FreeType=function(){return(Xa._FT_Done_FreeType=
Xa.asm.C).apply(null,arguments)};Xa._malloc=function(){return(Xa._malloc=Xa.asm.D).apply(null,arguments)};var Oi=Xa._realloc=function(){return(Oi=Xa._realloc=Xa.asm.E).apply(null,arguments)};Xa._free=function(){return(Xa._free=Xa.asm.F).apply(null,arguments)};Xa._ASC_FT_Malloc=function(){return(Xa._ASC_FT_Malloc=Xa.asm.G).apply(null,arguments)};Xa._ASC_FT_Free=function(){return(Xa._ASC_FT_Free=Xa.asm.H).apply(null,arguments)};Xa._ASC_FT_Init=function(){return(Xa._ASC_FT_Init=Xa.asm.I).apply(null,
arguments)};Xa._ASC_FT_Open_Face=function(){return(Xa._ASC_FT_Open_Face=Xa.asm.J).apply(null,arguments)};Xa._ASC_FT_SetCMapForCharCode=function(){return(Xa._ASC_FT_SetCMapForCharCode=Xa.asm.K).apply(null,arguments)};Xa._ASC_FT_GetFaceInfo=function(){return(Xa._ASC_FT_GetFaceInfo=Xa.asm.L).apply(null,arguments)};Xa._ASC_FT_GetFaceMaxAdvanceX=function(){return(Xa._ASC_FT_GetFaceMaxAdvanceX=Xa.asm.M).apply(null,arguments)};Xa._ASC_FT_GetKerningX=function(){return(Xa._ASC_FT_GetKerningX=Xa.asm.N).apply(null,
arguments)};Xa._ASC_FT_Glyph_Get_CBox=function(){return(Xa._ASC_FT_Glyph_Get_CBox=Xa.asm.O).apply(null,arguments)};Xa._ASC_FT_Get_Glyph_Measure_Params=function(){return(Xa._ASC_FT_Get_Glyph_Measure_Params=Xa.asm.P).apply(null,arguments)};Xa._ASC_FT_Get_Glyph_Render_Params=function(){return(Xa._ASC_FT_Get_Glyph_Render_Params=Xa.asm.Q).apply(null,arguments)};Xa._ASC_FT_Get_Glyph_Render_Buffer=function(){return(Xa._ASC_FT_Get_Glyph_Render_Buffer=Xa.asm.R).apply(null,arguments)};Xa._ASC_FT_Set_Transform=
function(){return(Xa._ASC_FT_Set_Transform=Xa.asm.S).apply(null,arguments)};Xa._ASC_FT_Set_TrueType_HintProp=function(){return(Xa._ASC_FT_Set_TrueType_HintProp=Xa.asm.T).apply(null,arguments)};var Ee=Xa._setThrew=function(){return(Ee=Xa._setThrew=Xa.asm.U).apply(null,arguments)},Ke=Xa.dynCall_vii=function(){return(Ke=Xa.dynCall_vii=Xa.asm.V).apply(null,arguments)},Yc=Xa.dynCall_iii=function(){return(Yc=Xa.dynCall_iii=Xa.asm.W).apply(null,arguments)},Vi=Xa.dynCall_iiii=function(){return(Vi=Xa.dynCall_iiii=
Xa.asm.X).apply(null,arguments)},we=Xa.dynCall_iiiii=function(){return(we=Xa.dynCall_iiiii=Xa.asm.Y).apply(null,arguments)},md=Xa.stackSave=function(){return(md=Xa.stackSave=Xa.asm.Z).apply(null,arguments)},pc=Xa.stackRestore=function(){return(pc=Xa.stackRestore=Xa.asm._).apply(null,arguments)};Xa.dynCall_vi=function(){return(Xa.dynCall_vi=Xa.asm.$).apply(null,arguments)};Xa.asm=lb;var Ie;kf=function ki(){Ie||Ta();Ie||(kf=ki)};Xa.run=Ta;if(Xa.preInit)for("function"==typeof Xa.preInit&&(Xa.preInit=
[Xa.preInit]);0<Xa.preInit.length;)Xa.preInit.pop()();Ta();f.AscFonts=f.AscFonts||{};nc=f.AscFonts;nc.pHg=function(){return Xa._ASC_FT_Init()};nc.TKg=35;nc.G9g=38;nc.UKg=40;nc.nIg=function(e,f){Xa._ASC_FT_Set_TrueType_HintProp(e,f)};nc.qHg=function(e){var f=Xa._ASC_FT_Malloc(e.size);Xa.HEAP8.set(e.data,f);return{yUg:!0,data:f,oi:e.size}};nc.IYd=function(e){var f=nc.Nac[e];f&&!0!==f.yUg&&(f=nc.qHg(nc.Nac[e]),nc.Nac[e]=null,nc.Nac[e]=f)};pb.prototype.load=function(e){if(e=Xa._ASC_FT_GetFaceInfo(e)){var f=
new Int32Array(Xa.HEAP8.buffer,e,Math.min(Xa.HEAP8.length-e>>2,250)),z=0;this.GUa=Math.abs(f[z++]);this.N7=f[z++];this.R_=f[z++];this.height=f[z++];this.u0=f[z++];this.nJc=f[z++];this.uM=f[z++];this.U8b=f[z++];this.MSc=f[z++];this.h3d=f[z++];for(var La=f[z++];La;)this.b7+=String.fromCharCode(La),La=f[z++];for(La=f[z++];La;)this.iHa+=String.fromCharCode(La),La=f[z++];this.TPf=f[z++];this.pCg=f[z++];this.kCg=f[z++];this.Rbg=f[z++];this.Sbg=f[z++];this.oCg=f[z++];this.Pbg=f[z++];this.Qbg=f[z++];this.mCg=
f[z++];z++;this.nCg=nc.uV.kR(f[z++]);z++;z++;z++;z++;this.lCg=f[z++];this.Hxg=f[z++];this.Gxg=f[z++];La=f[z++];for(var x=0;x<La;x++)this.oPf.push(f[z++]);Xa._ASC_FT_Free(e)}};nc.vGg=pb;nc.f8g=sc;nc.e8g=kc;nc.zVf=function(e,f,z){return Xa._ASC_FT_Open_Face(e,f.data,f.oi,z)};nc.cIg=function(e,f,z){e=Xa._ASC_FT_Get_Glyph_Measure_Params(e,f?1:0);if(!e)return null;var La=15;f&&(La=Xa.HEAP32[e>>2]);var x=new Int32Array(Xa.HEAP8.buffer,e,4*La),Oa=new sc;Oa.Lsg=x[1];Oa.Nsg=x[2];Oa.Ksg=x[3];Oa.Msg=x[4];Oa.width=
x[5];Oa.height=x[6];Oa.roa=x[7];Oa.Txa=x[8];Oa.nua=x[9];Oa.Lna=x[10];Oa.IIa=x[11];Oa.pHa=x[12];Oa.WHc=x[13];Oa.GRc=x[14];if(f){z.start(f);for(var Qa=15;Qa<La;)switch(x[Qa++]){case 0:z.vpg(x[Qa++],x[Qa++],f);break;case 1:z.mpg(x[Qa++],x[Qa++],f);break;case 2:z.Cog(x[Qa++],x[Qa++],x[Qa++],x[Qa++],f);break;case 3:z.Fog(x[Qa++],x[Qa++],x[Qa++],x[Qa++],x[Qa++],x[Qa++],f)}z.end(f)}Xa._ASC_FT_Free(e);return Oa};nc.ykg=function(e,f){e=Xa._ASC_FT_Get_Glyph_Render_Params(e,f);if(!e)return null;f=new Int32Array(Xa.HEAP8.buffer,
e,24);var z=new kc;z.left=f[0];z.top=f[1];z.width=f[2];z.rows=f[3];z.pitch=f[4];z.mode=f[5];Xa._ASC_FT_Free(e);return z};nc.sje=Xa._FT_Load_Glyph;nc.AVf=Xa._ASC_FT_Set_Transform;nc.tje=Xa._FT_Set_Char_Size;nc.CEf=Xa._ASC_FT_SetCMapForCharCode;nc.YHg=Xa._ASC_FT_GetKerningX;nc.XHg=Xa._ASC_FT_GetFaceMaxAdvanceX;nc.xkg=function(e,f,z){e=Xa._ASC_FT_Get_Glyph_Render_Buffer(e);e=new Uint8Array(Xa.HEAP8.buffer,e,f.pitch*f.rows);if(!z)return e;nc.R3b.VI(f.width,f.rows);z=0;var La=nc.R3b.i2a.data;if(f.pitch>=
f.width)for(var x=0;x<f.rows;++x,z+=f.pitch){var Oa=3+x*nc.R3b.pitch;for(var Qa=0;Qa<f.width;Qa++,Oa+=4)La[Oa]=e[z+Qa]}else{var Ta,Za;for(x=0;x<f.rows;++x,z+=f.pitch)for(Oa=3+x*nc.R3b.pitch,Qa=Za=Ta=0;Qa<f.width;Qa++,Oa+=4,Ta++)8==Ta&&(Ta=0,Za++),La[Oa]=e[z+Za]&1<<7-Ta?255:0}};nc.OJb()})(window,void 0);"use strict";
(function(f,e){function Ia(){this.gd=this.Px=null;this.B=this.G=this.R=0;this.Akb=this.Kza=null}function eb(){this.jya=this.yoa=this.RRc=this.d6a=0;this.DU=new Ia}function bb(){this.nla=this.Y_a=this.L7a=this.UTa=0;this.n8a=null}function cb(){this.gwd=this.iwd=this.hwd=this.OQc=this.fwd=this.ewd=this.XVb=this.Knb=0}function z(){this.whg;this.pda;this.qbg;this.UZc;this.fra;this.ez=new bb;this.aia=new cb;this.$Ha=!1;this.eA=null}function zb(){this.la=this.ka=0;this.Urb=25.4/72;this.Vrb=25.4/72;this.JHb=
!1;this.KVa=this.cI=this.vuc=this.shift=0}function Wb(){this.b6b={};this.gXf=function(f,z,Ta,Ia,La,Xa,lb){var Qa=f.Rv,cb=kb.Dp.hBa(z);if(e===cb||""==cb)return null;var bb=this.b6b[cb];if(!bb){bb=kb.h0a[kb.ueb[cb]];var yb=kb.i$a.RIa;f.SWf()&&(yb|=kb.i$a.Qna);f.XWf()&&(yb|=kb.i$a.Rna);bb=bb.CH(Za.MK,Qa,f.yJb,yb,f.EJb,f.P8b,e,!0);if(!bb)return null;bb.sYd();this.b6b[cb]=bb}if(!bb)return null;bb.a0d(f.yJb,f.EJb,f.P8b);f=f.G8b;Qa=bb.G8b;Qa[0]=f[0];Qa[1]=f[1];Qa[2]=f[2];Qa[3]=f[3];Qa[4]=f[4];Qa[5]=f[5];
bb.Ckb();return bb.N5b(z,Ta,Ia,La,Xa,lb,!0)};this.omb=function(){if(!this.Eje){this.Eje=!0;for(var e in this.b6b)this.b6b[e].omb();delete this.Eje}};this.O9b=function(){if(!this.Dje){this.Dje=!0;for(var e in this.b6b)this.b6b[e].O9b();delete this.Dje}}}var kb=f.AscFonts,Za=f.AscCommon;kb.g6c={zkg:0,I8g:1,eIg:2,K8g:4,dIg:8,Q8g:16,D8g:32,C8g:64,J8g:128,E8g:512,H8g:1024,F8g:2048,G8g:4096,Akg:8192,Bkg:32768,A8g:1048576,B8g:2097152,z8g:4194304};kb.hZd={Ckg:0,lIg:1,mIg:2,jIg:3,kIg:4,S8g:5};kb.R8g={P8g:(kb.hZd.Ckg&
15)<<16,N8g:(kb.hZd.lIg&15)<<16,O8g:(kb.hZd.mIg&15)<<16,L8g:(kb.hZd.jIg&15)<<16,M8g:(kb.hZd.kIg&15)<<16};kb.dXf=kb.g6c.zkg|kb.g6c.eIg|kb.g6c.Akg|kb.g6c.Bkg;kb.fJg=kb.g6c.zkg|kb.g6c.Akg|kb.g6c.Bkg;kb.N1g=function(e){kb.mob||(kb.mob=[],kb.mob.push(4352),kb.mob.push(4607),kb.mob.push(11904),kb.mob.push(40959),kb.mob.push(44032),kb.mob.push(55215),kb.mob.push(63744),kb.mob.push(64255),kb.mob.push(65280),kb.mob.push(65519),kb.mob.push(131072),kb.mob.push(173791),kb.mob.push(194560),kb.mob.push(195103));
if(e<kb.mob[0])return!1;for(var f=kb.mob,z=kb.mob.length,Ta=0;Ta<z;Ta+=2)if(e>=f[Ta]&&e<=f[Ta+1])return!0;return!1};var Mb=kb.R3b;kb.c$f=function(){};var Ta=kb.hZd.Ckg,pb={P5a:0,Fwc:1,m8b:2};Ia.prototype={$3f:function(e,f,z,Ta,La){if(e!=this.R||f!=this.G||z!=this.B)this.R=e,this.G=f,this.B=z,null!=this.Px?(this.gd.fillStyle=255==this.R&&255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.gd.fillRect(0,0,Ta,La)):(e=this.Kza,e.aCa.YSa.fillStyle=255==this.R&&255==
this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.Kza.aCa.YSa.fillRect(e.qc.Tc*e.za,e.qc.la,Ta,La))},a4f:function(e,f,z,Ta,La){if(e!=this.R||f!=this.G||z!=this.B)this.R=e,this.G=f,this.B=z,null!=this.Px?(this.gd.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.gd.fillRect(0,0,Ta,La)):(e=this.Kza,e.aCa.YSa.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.Kza.aCa.YSa.fillRect(e.qc.Tc*e.za,e.qc.la,Ta,La))},rQc:e,ve:function(e,f){0!=e&&0!=f&&(this.Px=document.createElement("canvas"),
this.Px.width=0==e?1:e,this.Px.height=0==f?1:f,this.gd=this.Px.getContext("2d"),this.gd.globalCompositeOperation="source-in")}};Ia.prototype.rQc=Za.Ue.X1a&&Za.Ue.yRc?Ia.prototype.$3f:Ia.prototype.a4f;eb.prototype={Y6f:function(e){var f;var z=!1;Math.max(this.yoa,this.jya)>(null==e.Lza?0:e.Lza.vEb)/10&&(z=!0);var Ta=f=0;z?(this.DU.ve(this.yoa,this.jya),e=this.DU.gd):(this.DU.Kza=e.Lza.mP(this.yoa,this.jya),e=this.DU.Kza.aCa.YSa,f=this.DU.Kza.qc.Tc*this.DU.Kza.za,Ta=this.DU.Kza.qc.la);0<this.yoa&&0<
this.jya&&e.putImageData(Mb.i2a,f,Ta,0,0,this.yoa,this.jya);if(null!=Mb.i2a){var La=3;z=4*(Mb.width-this.yoa);e=Mb.i2a.data;for(Ta=0;Ta<this.jya;Ta++){for(f=0;f<this.yoa;f++)e[La]=0,La+=4;La+=z}}},Md:function(e,f,z){var Ta=this.yoa,La=this.jya;if(null!=this.DU.Akb)e.drawImage(this.DU.Akb,0,0,Ta,La,f,z,Ta,La),this.DU.Akb=null;else if(null!=this.DU.Px)e.drawImage(this.DU.Px,0,0,Ta,La,f,z,Ta,La);else{var Za=this.DU.Kza;e.drawImage(Za.aCa.Cda,Za.qc.Tc*Za.za,Za.qc.la,Ta,La,f,z,Ta,La)}},yKf:function(e,
f,z,Ta,La,Za){if(null!=this.DU.Akb)e.drawImage(this.DU.Akb,Za,0,Ta,La,f,z,Ta,La),this.DU.Akb=null;else if(null!=this.DU.Px)e.drawImage(this.DU.Px,Za,0,Ta,La,f,z,Ta,La);else{var Ia=this.DU.Kza;e.drawImage(Ia.aCa.Cda,Ia.qc.Tc*Ia.za+Za,Ia.qc.la,Ta,La,f,z,Ta,La)}},zKf:function(e,f,z,Ta){var La=f,Za=z;f+=this.yoa;var Ia=z+this.jya,Qa=z=0,cb=this.yoa,bb=this.jya;La<Ta.je&&(z=Ta.je-La,La+=z,cb-=z);Za<Ta.t&&(Qa=Ta.t-Za,Za+=Qa,bb-=Qa);f>Ta.r&&(cb-=f-Ta.r);Ia>Ta.Wa&&(bb-=Ia-Ta.Wa);0>=cb||0>=bb||(null!=this.DU.Akb?
(e.drawImage(this.DU.Akb,z,Qa,cb,bb,La,Za,cb,bb),this.DU.Akb=null):null!=this.DU.Px?e.drawImage(this.DU.Px,z,Qa,cb,bb,La,Za,cb,bb):(Ta=this.DU.Kza,e.drawImage(Ta.aCa.Cda,Ta.qc.Tc*Ta.za+z,Ta.qc.la+Qa,cb,bb,La,Za,cb,bb)))},CEb:function(){null!=this.DU.Kza&&this.DU.Kza.aCa.CEb(this.DU.Kza)}};zb.prototype={start:function(){},vpg:function(e,f,z){this.JHb&&(z.Ay(),this.JHb=!1);this.cI=this.ka+e/64*this.Urb;this.KVa=this.la-f/64*this.Vrb;z.Rj(this.cI,this.KVa);return 0},kbg:function(e,f){return this.vpg(e.x,
e.y,f)},mpg:function(e,f,z){this.cI=this.ka+e/64*this.Urb;this.KVa=this.la-f/64*this.Vrb;z.Jc(this.cI,this.KVa);this.JHb=!0;return 0},POf:function(e,f){return this.mpg(e.x,e.y,f)},Cog:function(e,f,z,Ta,La){e=this.ka+e/64*this.Urb;f=this.la-f/64*this.Vrb;z=this.ka+z/64*this.Urb;Ta=this.la-Ta/64*this.Vrb;La.Zd(1/3*(this.cI+2*e),1/3*(this.KVa+2*f),1/3*(2*e+z),1/3*(2*f+Ta),z,Ta);this.cI=z;this.KVa=Ta;this.JHb=!0;return 0},Sbf:function(e,f,z){return this.Cog(e.x,e.y,f.x,f.y,z)},Fog:function(e,f,z,Ta,La,
Za,Ia){this.cI=this.ka+La/64*this.Urb;this.KVa=this.la-Za/64*this.Vrb;Ia.Zd(this.ka+e/64*this.Urb,this.la-f/64*this.Vrb,this.ka+z/64*this.Urb,this.la-Ta/64*this.Vrb,this.cI,this.KVa);this.JHb=!0;return 0},eKf:function(e,f,z,Ta){return this.Fog(e.x,e.y,f.x,f.y,z.x,z.y,Ta)},end:function(e){this.JHb&&(e.Ay(),this.JHb=!1)}};f.AscFonts.BEb=pb;f.AscFonts.dTf=function(){this.I8d="undefined"==typeof Float64Array?Array(6):new Float64Array(6);this.G8b="undefined"==typeof Float64Array?Array(6):new Float64Array(6);
this.wag=!0;this.vYc=!1;this.yJb=1;this.P8b=this.EJb=0;this.Abc=this.uYc=!1;this.ulb=0;this.K8b=new kb.yDf;this.mVd=0;this.WFa=this.h7=null;this.qpf=1;this.uDd=this.tDd=-1;this.eya=!1;this.xoa=this.Lra=this.CBa=this.fAa=this.L8d=0;this.E8b=[];this.F8b=[];this.Rv=null;this.vJb=this.Goe=this.Dhc=!0;this.Pvg=e;this.E6b=new Wb;this.xVf=function(e,f,z){z=kb.sje(e,f,z);if(0!=z&&this.Dhc){e=kb.sje(e,f,kb.dXf);if(0!=e)return z;this.Dhc=!1;return e}return z};this.VCe=function(){var e=this.I8d;this.uYc?(e[0]=
1,e[1]=0,e[2]=.3090169943749):(e[0]=1,e[1]=0,e[2]=0);e[3]=1;e[4]=0;e[5]=0;this.Ckb()};this.mYf=function(){var e=this.G8b;e[0]=1;e[1]=0;e[2]=0;e[3]=1;e[4]=0;e[5]=0;this.Hfe()};this.Hfe=function(){this.vJb=!0;var e=this.G8b;1==e[0]&&0==e[1]&&0==e[2]&&1==e[3]&&(this.vJb=!1,this.Ckb())};this.Ckb=function(){var e=this.I8d,f=this.G8b;kb.AVf(this.h7,65536*(e[0]*f[0]+e[1]*f[2])>>0,65536*(e[0]*f[1]+e[1]*f[3])>>0,65536*(e[2]*f[0]+e[3]*f[2])>>0,65536*(e[2]*f[1]+e[3]*f[3])>>0)};this.a0d=function(e,f,z){f=f+.5>>
0;z=z+.5>>0;var Ta=e/this.yJb;if((Ta=1.001<Ta||.999>Ta?!0:!1)||f!=this.EJb||z!=this.P8b)this.EJb=f,this.P8b=z,Ta&&(this.yJb=e,this.Ckb()),this.qpf=this.EJb/72*this.yJb,this.mVd=kb.tje(this.h7,0,64*e>>0,f,z),this.omb()};this.omb=function(){this.Y9b();this.O9b();this.E6b&&this.E6b.omb()};this.O9b=function(){this.E8b=[];this.F8b=[];this.E6b&&this.E6b.O9b()};this.Y9b=function(){if(null!=this.Rv&&null!=this.Rv.Lza){var e=this.E8b,f;for(f in e)null!=e[f].eA&&e[f].eA.CEb();e=this.F8b;for(f in e)null!=e[f].eA&&
e[f].eA.CEb()}};this.i5a=function(e,f,z,Ta,La,Za){var Ia=this.G8b,Qa=Ia[0]==e&&Ia[1]==-f&&Ia[2]==-z&&Ia[3]==Ta;if(Qa&&Ia[4]==La&&Ia[5]==Za)return!1;Ia[0]=e;Ia[1]=-f;Ia[2]=-z;Ia[3]=Ta;Ia[4]=La;Ia[5]=Za;Qa||this.omb();this.Hfe();return!0};this.NEf=function(e){var f=kb.CEf(this.h7,e);if(0<f)return f;-1!=this.uDd&&61440>e&&(f=kb.CEf(this.h7,e+61440));return f};this.N5b=function(f,Za,Ia,cb,La,Xa,lb){var Qa=new z;Qa.whg=f;var bb=this.eya?f:kb.CEf(this.h7,f);0>=bb&&!this.eya&&-1!=this.uDd&&61440>f&&(bb=
kb.CEf(this.h7,f+61440));if(0>=bb){if(!0===lb)return null;if(!this.eya&&this.E6b&&(bb=this.E6b.gXf(this,f,Za,Ia,cb,La,Xa)))return bb;if(0<=this.tDd)bb=this.tDd,Qa.pda=pb.Fwc;else return Qa.pda=pb.m8b,Qa.UZc=-1,Qa.fra=(kb.XHg(this.h7)>>6)/2,Qa}else Qa.pda=pb.P5a;Qa.UZc=bb;Qa.qbg=0;var yb=this.WVf();if(this.eya||!Za||this.Abc||!kb.N1g(f))yb|=kb.g6c.dIg;if(this.xVf(this.h7,bb,yb))return Qa;f=null;e!==cb&&(f=new zb,f.Urb=25.4/this.EJb,f.Vrb=25.4/this.P8b,La!==e&&(f.ka=La),Xa!==e&&(f.la=Xa));La=kb.cIg(this.h7,
cb,f);if(null==La||e!==cb)return Qa;cb=65535!=this.WFa.TPf&&800<=this.WFa.pCg?!0:!1;Qa.fra=La.WHc*this.qpf/this.xoa;this.Abc&&this.Rv.iFf&&!cb&&(Qa.fra+=1);Qa.ez.UTa=La.Lsg>>6;Qa.ez.L7a=La.Ksg>>6;Qa.ez.Y_a=La.Nsg>>6;Qa.ez.nla=La.Msg>>6;Xa=Qa.aia;Xa.Knb=La.width>>6;Xa.XVb=La.height>>6;Xa.ewd=La.Txa>>6;Xa.fwd=La.nua>>6;Xa.OQc=La.roa>>6;Xa.hwd=La.IIa>>6;Xa.iwd=La.pHa>>6;Xa.gwd=La.Lna>>6;if(lb&&0==Xa.OQc&&0==La.width)return null;if(!Za){if(Ia&&(Za=kb.ykg(this.h7,Ta))){cb=kb.xkg(this.h7,Za,!1);Za=Qa.ez;
f=cb.data;Ia=cb.width;lb=cb.rows;bb=cb.pitch;cb={ZWc:0,$Wc:0,V5f:0,U5f:0};yb=!1;for(La=0;La<Ia;La++){var sc=4*La+3;for(Xa=0;Xa<lb;Xa++,sc+=bb)if(0!=f[sc]){yb=!0;break}if(yb)break;cb.ZWc++}yb=!1;for(La=Ia-1;0<=La;La--){sc=4*La+3;for(Xa=0;Xa<lb;Xa++,sc+=bb)if(0!=f[sc]){yb=!0;break}if(yb)break;cb.V5f++}yb=!1;for(Xa=0;Xa<lb;Xa++){sc=Xa*bb+3;for(La=0;La<Ia;La++,sc+=4)if(0!=f[sc]){yb=!0;break}if(yb)break;cb.$Wc++}yb=!1;for(Xa=lb-1;0<=Xa;Xa--){sc=Xa*bb+3;for(La=0;La<Ia;La++,sc+=4)if(0!=f[sc]){yb=!0;break}if(yb)break;
cb.U5f++}if(null!=Mb.i2a)for(f=3,bb=4*(Mb.width-Ia),yb=Mb.i2a.data,Xa=0;Xa<lb;Xa++){for(La=0;La<Ia;La++)yb[f]=0,f+=4;f+=bb}Za.n8a=cb}return Qa}Qa.$Ha=!0;Za=kb.ykg(this.h7,Ta);if(!Za||0==Za.pitch)return Qa;Qa.eA=new eb;Qa.eA.d6a=Za.left;Qa.eA.RRc=Za.top;Qa.eA.yoa=Za.width;Qa.eA.jya=Za.rows;kb.xkg(this.h7,Za,!0);if(this.Abc&&this.wag&&!cb)for(Qa.eA.yoa++,Za=Qa.eA.yoa,Ia=Qa.eA.jya,Xa=Mb.i2a.data,La=lb=0;lb<Ia;++lb,La+=Mb.pitch)for(cb=Za-1;0<=cb;--cb)0!=cb&&(f=La+4*cb+3,Xa[f]=Za-1==cb?Xa[f-4]:Math.min(255,
Xa[f-4]+Xa[f]));Qa.eA.Y6f(this.Rv);return Qa};this.dda=function(f){if(0>=f.ZH)return!0;var z=0,Ta=0;this.vJb&&this.Ckb();for(var Za=!1===this.eya?this.E8b:this.F8b,La=0;La<f.ZH;++La){var Ia=f.TMb(La).rSa,lb=Za[Ia];e==lb&&(Za[Ia]=this.N5b(Ia,!1),lb=Za[Ia]);Ia=lb.UZc;var Qa=lb.pda;pb.m8b==Qa?(f.gPc(La,Ta,0),f.aPc(La,0,0,0,0),f.QQb(La,pb.m8b),Ta+=lb.fra+this.ulb,z=0):(pb.Fwc==Qa?f.QQb(La,pb.Fwc):f.QQb(La,pb.P5a),this.vYc&&z&&0<La&&f.TMb(La).pda==f.TMb(La-1).pda&&(Ta+=this.Sgc(z,Ia)),z=f.n_+Ta,Qa=f.o_+
0,f.gPc(La,f.Yha[4]+z*f.Yha[0]+Qa*f.Yha[2]-f.n_,f.Yha[5]+z*f.Yha[1]+Qa*f.Yha[3]-f.o_),z=lb.aia,f.nGf(La,z.Knb,z.XVb,z.OQc,z.ewd,z.fwd,z.gwd,z.hwd,z.iwd),f.aPc(La,lb.ez.UTa,lb.ez.nla,lb.ez.L7a,lb.ez.Y_a),Ta+=lb.fra+this.ulb,z=Ia)}f.oBb=Ta+f.n_;f.g2b=0+f.o_};this.cc=function(f){if(0>=f.ZH)return!0;this.vJb&&this.Ckb();for(var z=0,Ta=0,Za=!1===this.eya?this.E8b:this.F8b,La=0;La<f.ZH;++La){var Ia=f.TMb(La),lb=Ia.rSa,Qa=Za[lb];if(e==Qa||null==Qa.eA)Za[lb]=this.N5b(lb,!0),Qa=Za[lb];lb=Qa.UZc;var cb=Qa.pda;
pb.m8b==cb?(f.gPc(La,Ta,0),f.aPc(La,0,0,0,0),f.QQb(La,pb.m8b),Ta+=Qa.fra+this.ulb,z=0):(pb.Fwc==cb?f.QQb(La,pb.Fwc):f.QQb(La,pb.P5a),this.vYc&&z&&0<La&&f.TMb(La).pda==f.TMb(La-1).pda&&(Ta+=this.Sgc(z,lb)),z=f.n_+Ta,cb=f.o_+0,f.gPc(La,f.Yha[4]+z*f.Yha[0]+cb*f.Yha[2]-f.n_,f.Yha[5]+z*f.Yha[1]+cb*f.Yha[3]-f.o_),Ia.aia=Qa.aia,f.aPc(La,Qa.ez.UTa,Qa.ez.nla,Qa.ez.L7a,Qa.ez.Y_a),Ta+=Qa.fra+this.ulb,Ia.$Ha=Qa.$Ha,Ia.eA=Qa.eA,z=lb)}f.oBb=Ta+f.n_;f.g2b=0+f.o_};this.YNd=function(f){this.vJb&&this.Ckb();var z=
f.dM[0],Ta=z.rSa,Za=!1===this.eya?this.E8b:this.F8b,La=Za[Ta];if(e==La||null==La.eA&&!1===La.$Ha)Za[Ta]=this.N5b(Ta,!0),La=Za[Ta];if(La)if(Ta=La.pda,z.pda=La.pda,pb.m8b==Ta)z.Pz=0,z.Uy=0,z.BJa=0,z.eBa=0,z.VTa=0,z.AJa=0;else{Ta=f.n_;Za=f.o_;var Ia=f.Yha;z.Pz=Ia[4]+Ta*Ia[0]+Za*Ia[2]-f.n_;z.Uy=Ia[5]+Ta*Ia[1]+Za*Ia[3]-f.o_;z.aia=La.aia;z.$Ha=La.$Ha;z.eA=La.eA;f.oBb=La.fra+this.ulb+f.n_;f.g2b=f.o_}};this.W0=function(f,z){this.vJb&&this.Ckb();var Ta=!1===this.eya?this.E8b:this.F8b,Za=Ta[f];e==Za&&(Ta[f]=
this.N5b(f,!1,z),Za=Ta[f]);return Za};this.XVf=function(e,f,z,Ta){this.vJb&&this.Ckb();this.N5b(e,!1,!1,f,z,Ta)};this.QEf=function(e,f){var z=e.ZH;if(!(0>=z))for(var Ta=0;Ta<z;++Ta){var La=e.dM[Ta],Za=e.n_+25.4*La.Pz/this.EJb,Ia=e.o_+25.4*La.Uy/this.P8b;f.Gj();this.XVf(La.rSa,f,Za,Ia);f.St();f.Gu()}};this.WVf=function(){return this.Dhc&&this.Goe?this.Rv.f_d:kb.dXf};this.Sgc=function(e,f){return kb.YHg(this.h7,e,f)>>6};this.IHa=function(e){this.eya!=e&&(this.eya=e)};this.lGf=function(e){this.ulb=e};
this.SWf=function(){return this.Abc?!0:-1!=this.WFa.iHa.indexOf("Bold")?!0:!1};this.XWf=function(){return this.uYc?!0:-1!=this.WFa.iHa.indexOf("Italic")?!0:!1};this.pGf=function(e){this.uYc!=e&&(this.omb(),this.uYc=e,this.VCe())};this.oGf=function(e){this.Abc!=e&&(this.omb(),this.Abc=e)};this.a_d=function(){return 0==this.mVd};this.q$a=function(){return this.fAa};this.dWa=function(){return this.CBa};this.PH=function(){return this.Lra};this.sYd=function(){this.Goe=this.Dhc=!0};this.Btg=function(){var e=
this.WFa,f=[];f.push(e.GUa);65535!=e.TPf?(f.push(e.Rbg),f.push(-e.Sbg)):(f.push(e.Gxg),f.push(e.Hxg));return f};this.zKg=function(e,f){this.h7=e;this.WFa=new kb.vGg;this.WFa.load(this.h7);this.xoa=this.WFa.GUa;this.fAa=this.WFa.N7;this.CBa=this.WFa.R_;this.Lra=this.WFa.height;if(f.nFf&&65535!=this.WFa.TPf)if(f.iOd){var z=this.WFa.Rbg,Ta=-this.WFa.Sbg;if(0!=(this.WFa.nCg&770703360)){var La=.3*(z-Ta)>>0;z+=La+1>>1;Ta-=La>>1}this.WFa.height<z-Ta&&(this.fAa=z,this.CBa=Ta,this.Lra=z-Ta)}else 128==(this.WFa.kCg&
128)&&(this.fAa=this.WFa.Pbg,this.CBa=this.WFa.Qbg,this.Lra=this.WFa.Pbg-this.WFa.Qbg+this.WFa.mCg);this.L8d=this.WFa.U8b;this.tDd=this.WFa.oCg;this.uDd=this.WFa.lCg;this.mVd=kb.tje(e,0,64*this.yJb,0,0);this.mYf();this.VCe();!0===f.vYc&&(this.vYc=0!=(this.WFa.u0&64)?!0:!1);if(0!=this.WFa.oPf.length)for(this.Pvg=[],e=this.WFa.oPf.length-1;0<=e;e--)this.Pvg[this.WFa.oPf[e]>>6]=!0}};f.AscFonts.OJb()})(window);"use strict";
(function(f){function e(){this.sM=Ia.pHg();this.YFa=null;this.SPf=function(e,f){e=Ia.zVf(this.sM,e,f);if(!e)return null;f=new Ia.dTf;f.zKg(e,this.YFa);return f.a_d()?f:null};this.e$d=function(e,f){f=e&&f?Ia.UKg:Ia.TKg;this.YFa.f_d=e?Ia.fJg:Ia.dXf;Ia.nIg(this.sM,f)}}var Ia=f.AscFonts;f.AscFonts.GKf=function(f){var bb=new e;bb.YFa=f;bb.e$d(f.pRd,f.qRd);f.eFb=bb;Ia.c$f()};f.AscFonts.rZg=function(){};f.AscFonts.OJb()})(window);
